import time

while True:
    user = input("Enter 1 for a new image, 0 to exit the program: ")
    if user == "1":
        # write the command to the rng service
        rng_service = open("prng-service.txt", "w")
        rng_service.write("run")
        rng_service.close()
        time.sleep(2)
        # read the rng value from the file
        rng_service = open("prng-service.txt", "r")
        num = rng_service.read()
        rng_service.close()
        # write the value to the image service
        img_service = open("image-service.txt", "w")
        img_service.write(num)
        img_service.close()
        time.sleep(2)
        # read the path generated by the image service
        img_service = open("image-service.txt", "r")
        path = img_service.read()
        print(path, '\n')
        img_service.close()
    else:
        break


